[package]
name = "mpc-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
eyre = "0.6.12"
intmap = "3.1.0"
oneshot = "0.1.11"
parking_lot = "0.12.3"
rayon = "1.10.0"
tracing = "0.1.41"
